version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ghaderi
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./back-end
    container_name: backend
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    volumes:
      - ./back-end:/app
    command: npm start

  frontend:
    build:
      context: ./site
      dockerfile: Dockerfile
      args:
      - NEXT_PUBLIC_API_URL=http://localhost:4000  # 👈 browser uses this
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
        - NEXT_PUBLIC_API_URL=http://localhost:4000    # 👈 browser uses this
        - INTERNAL_API_URL=http://backend:4000 

volumes:
  db_data: